name: CI
on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'Cargo.toml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'Cargo.toml'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup component add clippy
          rustup component add rustfmt
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo fmt --all -- --check
      - run: cargo test --all-features